CREATE TABLE tallyit_games (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_name TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    group_id INTEGER
        REFERENCES tallyit_groups(id) ON DELETE CASCADE NOT NULL
);