CREATE TABLE tallyit_player_scores (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    player_name TEXT NOT NULL,
    score INTEGER DEFAULT 0 NOT NULL,
    game_id INTEGER
        REFERENCES tallyit_games(id) ON DELETE CASCADE NOT NULL,
    group_id INTEGER
        REFERENCES tallyit_groups(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
);